// Code generated by entc, DO NOT EDIT.

package blog

const (
	// Label holds the string label denoting the blog type in the database.
	Label = "blog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDefaultPageNum holds the string denoting the default_page_num field in the database.
	FieldDefaultPageNum = "default_page_num"
	// FieldBlogName holds the string denoting the blog_name field in the database.
	FieldBlogName = "blog_name"
	// FieldBtitle holds the string denoting the btitle field in the database.
	FieldBtitle = "btitle"
	// FieldSubtitle holds the string denoting the subtitle field in the database.
	FieldSubtitle = "subtitle"
	// FieldBeian holds the string denoting the beian field in the database.
	FieldBeian = "beian"
	// FieldCopyRight holds the string denoting the copy_right field in the database.
	FieldCopyRight = "copy_right"

	// Table holds the table name of the blog in the database.
	Table = "blogs"
)

// Columns holds all SQL columns for blog fields.
var Columns = []string{
	FieldID,
	FieldDefaultPageNum,
	FieldBlogName,
	FieldBtitle,
	FieldSubtitle,
	FieldBeian,
	FieldCopyRight,
}
