
# 启动时是否打印配置参数
PrintConfig = true

[server]
RunMode = "debug"
HTTPPort = 8000


[Blog]
# 默认每页文章的数量
DefaultPageNum = 10
# 后台登录用户名
UserName = "peanut"
Password = "peanut"
Email = "hjzhaofan@gmail.com"
BlogName = "PeanutBlog"
subtitle = "Stay hungry Stay foolish"
# 备案信息
beian = "京ICP备17004069号-2"
# footer显示名称及tab标题
btitle = "Peanut's Blog"
# 版权声明
copyright = "本站使用「<a href='//creativecommons.org/licenses/by/4.0/'>署名 4.0 国际</a>」创作共享协议，转载请注明作者及原网址。"

[Log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
Level = 5
# 日志格式（支持输出格式：text/json）
Format = "text"
# 日志输出(支持：stdout/stderr/file)
Output = "stdout"
# 指定日志输出的文件路径
OutputFile = "logs/blog.log"

[MySQL]
# 连接地址
Host = "10.211.55.3"
# 连接端口
Port= 3306
# 用户名
User = "root"
# 密码
Password = "123456"
# 数据库
DBName = "goBlog"
# 连接参数
Parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"







