// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
